language: csharp  
sudo: required  
dist: trusty  
mono: none
dotnet: 2.1.802
solution: SilverHorn.Cloo.Tests.sln

before_script:
  - dotnet restore
script:  
  - dotnet test ./silver-horn-cloo-tests -c Release -f netcoreapp2.1