language: csharp
sudo: required
dist: trusty
mono: none
dotnet: 2.1
solution: silver-horn-opencl.sln

addons:
  sonarcloud:
    organization: "kashinoleg"
    token:
      secure: $SONAR_TOKEN

git:
  depth: false

install:
  - dotnet tool install --global dotnet-sonarscanner
  - dotnet restore

before_script:
  - export PATH="$PATH:$HOME/.dotnet/tools"

script:
  - dotnet sonarscanner begin /d:sonar.login="$SONAR_TOKEN" /d:sonar.host.url="https://sonarcloud.io" /k:"kashinoleg_silver-horn-opencl" /o:"kashinoleg" /n:"silver-horn-opencl" /v:"1.0.$TRAVIS_BUILD_NUMBER" /d:sonar.links.homepage="https://github.com/kashinoleg/silver-horn-opencl" /d:sonar.links.ci="https://travis-ci.org/kashinoleg/silver-horn-opencl" /d:sonar.links.scm="https://github.com/kashinoleg/silver-horn-opencl" /d:sonar.links.issue="https://github.com/kashinoleg/silver-horn-opencl/issues" /d:sonar.sources="." /d:sonar.language="cs" /d:sonar.c.file.suffixes="-" /d:sonar.cpp.file.suffixes="-" /d:sonar.objc.file.suffixes="-" /d:sonar.sourceEncoding="UTF-8" /d:sonar.language="cs" /d:sonar.exclusions="**/bin/**/*,**/obj/**/*" || true
  - dotnet build silver-horn-opencl.sln -c Release
# /d:sonar.cs.opencover.reportsPaths="**/coverage.opencover.xml"
#  - dotnet test silver-horn-cloo-tests/silver-horn-cloo-tests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
  - dotnet sonarscanner end /d:sonar.login="$SONAR_TOKEN" || true

cache:
  directories:
    - '$HOME/.nuget/packages'
    - '$HOME/.local/share/NuGet/Cache'
    - '$HOME/.sonar/cache'

